
- name: Install Ansible and AWX/Tower Python dependencies
  pip:
    name: "{{ awx_pip_pkgs }}"
    state: present
  tags:
    - awx_settings
    - awx_credentials
    - awx_projects
    - awx_inventories
    - awx_jobs
    - awx_configuration

- name: Import checks for AWX/Tower containers
  import_tasks: verify-running.yml
  tags:
    - awx_settings
    - awx_credentials
    - awx_projects
    - awx_inventories
    - awx_jobs
    - awx_configuration

- import_tasks: awx-config-settings.yml
  tags:
    - awx_settings
  when:
    - awx_containers_running

- import_tasks: awx-config-credentials.yml
  tags:
    - awx_credentials
  when:
    - awx_containers_running

- import_tasks: awx-config-projects.yml
  tags:
    - awx_projects
  when:
    - awx_containers_running

- import_tasks: awx-config-inventories.yml
  tags:
    - awx_inventories
  when:
    - awx_containers_running

- import_tasks: awx-config-jobs.yml
  tags:
    - awx_jobs
  when:
    - awx_containers_running
