---

- name: Update tower settings
  uri:
    url: "{{ awx_web_url }}/api/v2/settings/all/"
    user: "{{ awx_admin_user }}"
    password: "{{ awx_admin_password }}"
    method: PATCH
    body: |
      {
      "{{ item.name }}": {{ item.value | to_json }}
      }
    force_basic_auth: True
    body_format: json
    validate_certs: False
    return_content: True
  loop: "{{ awx_config_settings }}"
  when:
    - awx_config_settings is defined
    - awx_config_settings != None


- name: Add email notification
  awx.awx.tower_notification:
    name: ansible-notification
    notification_type: email
    username: "{{ vault_email_user }}"
    password: "{{ vault_email_password }}"
    sender: "{{ vault_email_user }}"
    recipients:
      - "{{ awx_notification_email }}"
    host: "{{ vault_email_server }}"
    port: 587
    use_tls: yes
    use_ssl: no
    state: present
    validate_certs: no
    tower_host: "{{ awx_web_url }}"
    tower_username: "{{ awx_admin_user }}"
    tower_password: "{{ awx_admin_password }}"
  when:
    - awx_notification_email is defined
    - awx_notification_email != 'None'
  changed_when: False
