---

- name: Update Tower Settings
  awx.awx.tower_settings:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    validate_certs: no
    tower_host: "{{ awx_web_url }}"
    tower_username: "{{ awx_admin_user }}"
    tower_password: "{{ awx_admin_password }}"
  loop: "{{ awx_config_settings | dict2items }}"
  when:
    - awx_config_settings is defined
    - awx_config_settings != None
  changed_when: False

- name: Add email notification
  awx.awx.tower_notification:
    name: ansible-notification
    notification_type: email
    username: "{{ vault_email_user }}"
    password: "{{ vault_email_password }}"
    sender: "{{ vault_email_user }}"
    recipients:
      - "{{ awx_notification_email }}"
    host: "{{ vault_email_server }}"
    port: 587
    use_tls: yes
    use_ssl: no
    state: present
    validate_certs: no
    tower_host: "{{ awx_web_url }}"
    tower_username: "{{ awx_admin_user }}"
    tower_password: "{{ awx_admin_password }}"
  when:
    - awx_notification_email is defined
    - awx_notification_email != 'None'
  changed_when: False
