- name: Import checks for AWX/Tower containers
  import_tasks: verify-running.yml

- name: Run AWX/Tower custom configuration tasks
  block:

    - import_tasks: awx-config-settings.yml
      tags:
        - awx-settings
    - import_tasks: awx-config-credentials.yml
      tags:
        - awx-credentials
    - import_tasks: awx-config-projects.yml
      tags:
        - awx-projects
    - import_tasks: awx-config-inventories.yml
      tags:
        - awx-inventories
    - import_tasks: awx-config-jobs.yml
      tags:
        - awx-jobs

  when: awx_containers_running
