- name: Import checks for AWX/Tower containers
  import_tasks: verify-running.yml
  tags:
    - awx-settings
    - awx-credentials
    - awx-projects
    - awx-inventories
    - awx-jobs
    - awx-configuration

- import_tasks: awx-config-settings.yml
  tags:
    - awx-settings
  when:
    - awx_containers_running

- import_tasks: awx-config-credentials.yml
  tags:
    - awx-credentials
  when:
    - awx_containers_running

- import_tasks: awx-config-projects.yml
  tags:
    - awx-projects
  when:
    - awx_containers_running

- import_tasks: awx-config-inventories.yml
  tags:
    - awx-inventories
  when:
    - awx_containers_running

- import_tasks: awx-config-jobs.yml
  tags:
    - awx-jobs
  when:
    - awx_containers_running
