---

- name: Create Additional Tower Credential Types
  awx.awx.tower_credential_type:
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    kind: "{{ item.kind }}"
    inputs: "{{ item.inputs | default(omit) }}"
    injectors: "{{ item.injectors | default(omit) }}"
    state: present
    validate_certs: no
    tower_host: "{{ awx_web_url }}"
    tower_username: "{{ awx_admin_user }}"
    tower_password: "{{ awx_admin_password }}"
  loop: "{{ awx_credential_types }}"
  when:
    - awx_credential_types is defined
    - awx_credential_types != None

- name: Create Tower credentials
  awx.awx.tower_credential:
    name: "{{ item.name }}"
    organization: "{{ item.organization | default('Default') }}"
    state: "{{ item.state | default('present') }}"
    kind: "{{ item.kind | default(omit) }}"
    inputs: "{{ item.inputs | default(omit) }}"
    credential_type: "{{ item.credential_type | default(omit) }}"
    ssh_key_data: "{{ item.ssh_key_data | default(omit) }}"
    username: "{{ item.username | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    vault_id: "{{ item.vault_id | default(omit) }}"
    vault_password: "{{ item.vault_password | default(omit) }}"
    validate_certs: no
    tower_host: "{{ awx_web_url }}"
    tower_username: "{{ awx_admin_user }}"
    tower_password: "{{ awx_admin_password }}"
  loop: "{{ awx_credentials }}"
  when:
    - awx_credentials is defined
    - awx_credentials != None
  changed_when: False
  no_log: True


#- name: "Create Tower custom credential type for Foreman Dynamic Inventory (if present)"
#  awx.awx.tower_credential_type:
#    name: "{{ item.name }}"
#    description: "{{ item.description }}"
#    kind: "{{ item.kind }}"
#    inputs: "{{ item.inputs }}"
#    injectors: "{{ item.injectors }}"
#    state: present
#    validate_certs: no
#    tower_host: "{{ awx_web_url }}"
#    tower_username: "{{ awx_admin_user }}"
#    tower_password: "{{ awx_admin_password }}"
#  loop: "{{ awx_credential_types }}"
#  when:
#    - awx_credential_types is defined
#    - awx_credential_types != None


#- name: "Create Tower custom credential type for Foreman Dynamic Inventory"
#  tower_send:
#    tower_host: "{{ awx_web_url }}"
#    tower_username: "{{ awx_admin_user }}"
#    tower_password: "{{ awx_admin_password }}"
#    validate_certs: no
#    assets: "{{ lookup('template', 'foreman_credential_type.j2') }}"

#- debug:
#    msg: "{{ awx_credential_types | flatten }}"

#- name: "Create Tower credential for Foreman Dynamic Inventory"
#  tower_send:
#    tower_host: "{{ awx_web_url }}"
#    tower_username: "{{ awx_admin_user }}"
#    tower_password: "{{ awx_admin_password }}"
#    validate_certs: no
#    assets: "{{ lookup('template', 'foreman_credential.json.j2') }}"
#  loop: "{{ awx_credential_types }}"
#  when:
#    - item.name == "foreman.ini"
#  changed_when: False
