---

- name: Check for ca-trust in awxweb container
  shell: docker exec awxweb "test" "-f" "/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt"
  register: awx_web_catrust
  changed_when: False
  ignore_errors: yes

- name: Update CA trust in awxweb container
  command: docker exec awxweb '/usr/bin/update-ca-trust'
  register: awx_web_catrust_update
  when:
    - awx_web_catrust is failed

  #when: (awx_compose_config is defined and awx_compose_config.changed) or (awx_compose_start is defined and awx_compose_start.changed)

- name: Check for ca-trust in awx container
  shell: docker exec awx "test" "-f" "/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt"
  register: awx_catrust
  changed_when: False
  ignore_errors: yes

- name: Update CA trust in awx container
  command: docker exec awx '/usr/bin/update-ca-trust'
  register: awx_catrust_update
  when:
    - awx_catrust is failed
  #when: (awx_compose_config is defined and awx_compose_config.changed) or (awx_compose_start is defined and awx_compose_start.changed)


- name: Check ansible version in awx container
  shell: docker exec -t awx '/bin/pip3' 'show' 'ansible' | grep -i version | awk '{print $2}'
  register: awx_ansible_version
  changed_when: False
  ignore_errors: yes

#- debug:
#    msg: "{{ awx_ansible_version.stdout }}"

- name: Update ansible in awx container
  command: docker exec -t awx '/bin/pip3' 'install' '--upgrade' 'ansible'
  when: awx_ansible_version.stdout is version('2.9.0', '<')

- name: Check ansible version in awxweb container
  shell: docker exec -t awxweb '/bin/pip3' 'show' 'ansible' | grep -i version | awk '{print $2}'
  register: awxweb_ansible_version
  changed_when: False
  ignore_errors: yes


- name: Update ansible in awxweb container
  command: docker exec -t awxweb '/bin/pip3' 'install' '--upgrade' 'ansible'
  when: awxweb_ansible_version.stdout is version('2.9.0', '<')


- name: Update ansible in awxweb container
  command: docker exec -t awxweb '/bin/pip3' 'install' '--upgrade' 'ansible'
  when: awxweb_ansible_version.stdout is version('2.9.0', '<')

- name: Check for python requests in awx container
  shell: docker exec -t awx '/bin/pip3' 'show' 'requests'
  register: awx_requests_present
  changed_when: False
  ignore_errors: yes

- name: Install python requests in awx container
  command: docker exec -t awx '/bin/pip3' 'install' 'requests'
  when: awx_requests_present is failed

- name: Check for python redis in awx container
  shell: docker exec -t awx '/bin/pip3' 'show' 'redis'
  register: awx_redis_present
  changed_when: False
  ignore_errors: yes

- name: Install python redis in awx container
  command: docker exec -t awx '/bin/pip3' 'install' 'redis'
  when: awx_redis_present is failed
