---

- name: Import check for AWX/Tower containers
  import_tasks: verify-running.yml
  tags:
    - awx_container_tasks

- name: Run AWX Container Tasks
  block:

    - name: Check for ca-trust in awx_web_1 container
      shell: docker exec awx_web_1 "test" "-f" "/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt"
      register: awx_web_catrust
      changed_when: False
      ignore_errors: yes

    - name: Update CA trust in awx_web_1 container
      command: docker exec awx_web_1 '/usr/bin/update-ca-trust'
      register: awx_web_catrust_update
      when:
        - awx_web_catrust is failed

    - name: Check for ca-trust in awx container
      shell: docker exec awx_task_1 "test" "-f" "/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt"
      register: awx_catrust
      changed_when: False
      ignore_errors: yes

    - name: Update CA trust in awx container
      command: docker exec awx_task_1 '/usr/bin/update-ca-trust'
      register: awx_catrust_update
      when:
        - awx_catrust is failed

    - name: Update ansible in awx container
      command: docker exec -t awx_task_1 '/bin/python3' '-m' 'pip' 'install' '--upgrade' 'ansible'
      register: awxtask_ansible_upgrade
      changed_when: '"installed" in  awxtask_ansible_upgrade.stdout'


    - name: Update ansible in awx_web_1 container
      command: docker exec -t awx_web_1 '/bin/python3' '-m' 'pip' 'install' '--upgrade' 'ansible'
      register: awxweb_ansible_upgrade
      changed_when: '"installed" in  awxweb_ansible_upgrade.stdout'


    - name: Install python packages in awx container
      command: docker exec -t awx_task_1 '/bin/python3' '-m' 'pip' 'install' '--upgrade' '{{ item }}'
      loop: "{{ awx_container_python_pkgs }}"
      register: awxtask_python_upgrade
      changed_when: '"installed" in  awxtask_python_upgrade.stdout'


    - name: Install python packages in awx_web_1 container
      command: docker exec -t awx_web_1 '/bin/python3' '-m' 'pip' 'install' '--upgrade' '{{ item }}'
      loop: "{{ awx_container_python_pkgs }}"
      register: awxweb_python_upgrade
      changed_when: '"installed" in  awxweb_python_upgrade.stdout'

  when: awx_containers_running
  tags:
    - awx_container_tasks
