---

- name: Python <2.7 is incompatible
  fail:
    msg: Python 2.7 or greater is required
  when:
    - ansible_python.version.major == 2
    - ansible_python.version.minor <= 6

- name: uninstall deprecated python 2.7 docker pip modules
  pip:
    name: "{{ awx_docker_py26_pkgs }}"
    state: absent
  when:
    - ansible_python.version.major == 2
    - ansible_python.version.minor >= 7

- name: install python 2.7 docker pip modules
  pip:
    name: "{{ awx_docker_py27_pkgs }}"
    state: present
    executable: pip2
  when:
    - ansible_python.version.major == 2
    - ansible_python.version.minor >= 7

- name: install python3 docker modules
  pip:
    name: "{{ awx_docker_py3_pkgs }}"
    state: present
    executable: pip3
  when: ansible_python.version.major == 3