---
- name: "Disable SELinux, Configure FirewallD ports to ACCEPT [RHEL/CentOS]"
  block:
    - name: Disable SELinux
      selinux:
        state: disabled
    - name: Configure Firewalld allowed ports
      firewalld:
        port: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop: "{{ awx_allowed_ports }}"
  when: ansible_os_family == "RedHat"
  tags:
    - always
- name: Assure variables are set
  import_tasks: assertions.yml
  tags:
    - always

- name: Build config files for AWX services
  import_tasks: config-files.yml
  tags:
    - awx_config_files
    - awx_container_tasks

- name: Run docker exec container tasks
  import_tasks: container-tasks.yml
  tags:
    - never
    - awx_container_tasks

- name: Run AWX/Tower App Configuration
  import_tasks: awx-configuration.yml
  tags:
    - awx-configuration
    - never
